services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: Andromed@47
      POSTGRES_USER: rey
      POSTGRES_DB: sicilian-main
    volumes:
      - ./src/db/init:/docker-entrypoint-initdb.d
      - sicilian_defense_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  sicilian_defense_pgdata:
